# Generated by Django 3.2 on 2021-04-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0003_auto_20210428_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('songs', models.ManyToManyField(to='spotify_api.Song')),
            ],
        ),
    ]
