# Generated by Django 3.2 on 2021-05-01 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0004_curatedplaylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.CreateModel(
            name='OrderedPlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_api.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_api.song')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedCuratedPlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('curatedplaylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_api.curatedplaylist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_api.song')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedAlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_api.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_api.song')),
            ],
        ),
    ]
