# Generated by Django 3.2 on 2021-05-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0008_auto_20210501_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedplaylist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='orderedcuratedplaylistsong',
            name='curatedplaylist',
        ),
        migrations.RemoveField(
            model_name='orderedcuratedplaylistsong',
            name='song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='albumOrder',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_type',
            field=models.CharField(choices=[('Album', 'Album'), ('Playlist', 'Playlist'), ('CuratedPlaylist', 'CuratedPlaylist')], default='Playlist', max_length=20),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='CuratedPlaylist',
        ),
        migrations.DeleteModel(
            name='OrderedCuratedPlaylistSong',
        ),
    ]
