# Generated by Django 3.2 on 2021-05-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0009_auto_20210501_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotify_api.artist'),
        ),
    ]
