# Generated by Django 3.2 on 2021-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0010_playlist_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='img_url',
            field=models.CharField(default='kennebunkportrevival.png', max_length=100),
            preserve_default=False,
        ),
    ]
