# Generated by Django 3.2 on 2021-05-07 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0011_playlist_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spotify_api.playlist'),
            preserve_default=False,
        ),
    ]
