# Generated by Django 3.2 on 2021-05-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0012_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='img_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
